### PR TITLE
Feature/hiker 23

### PR DESCRIPTION
**Pull request by TamaraSchweiger**

### CODE REVIEW

**Review by SebastianGrief — CHANGES_REQUESTED** [review]
[The altitude is not updated for me for some reason. Service is connected but no updates received.] 
Edit2:  Works after restarting my device.
Tested on Fairphone 3 - Android 10

Edit:
Also the AltitudeUITest.kt tests fail for me. (Might be my device tho because I can see the updated textViews)

**Comment by chairete** [comment]
Seems to work fine on my device (Realme X2 Pro - Android 11)

AltitudeUITest.kt fail on my device but pass in the emulator

**Review by chairete — COMMENTED** [review]
Seems to work fine on my device (Realme X2 Pro - Android 11)

AltitudeUITest.kt fail on my device but pass in the emulator

**Comment by SebastianGrief** [comment]
> [The altitude is not updated for me for some reason. Service is connected but no updates received.]
> Edit2: Works after restarting my device.
> Tested on Fairphone 3 - Android 10
> 
> Edit:
> Also the AltitudeUITest.kt tests fail for me. (Might be my device tho because I can see the updated textViews)

Will be fixed by Hotfix because not part of the subtask.

**Review by SebastianGrief — APPROVED** [review]

**Pull request merged**
